on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  hello_world_job:
    permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    name: A job to get OIDC token and say hello
    steps:
      - uses: Sawthis/expose-jwt-action@main
        name: Get JWT token
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v4
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'https://github.com/github'
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Wojtek'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
