name: pull-go-lint

on:
  # This workflow is triggered by workflow controller.
  workflow_call:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: kyma-project/test-infra/.github/actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: '1.25.3'

      - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0