name: pull-build-test-out-org.yml
#  description: Build image for rotate-service-account
on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - "cmd/cloud-run/rotate-service-account/Dockerfile"
      - "cmd/cloud-run/rotate-service-account/*.go"
      - "pkg/**"
      - "go.mod"
      - "go.sum"

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: test-infra/rotate-service-account
      dockerfile: cmd/cloud-run/rotate-service-account/Dockerfile
      context: .
