name: test-pull-sync-external-images

on:
  pull_request:
    branches:
      - main
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - "external-images.yaml"
      - ".github/workflows/test-workflowe.yml"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout
jobs:
  sync-images:
    permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read # This is required for actions/checkout
    runs-on: ubuntu-latest
    name: Sync images
    steps:
      - name: Verify repository owner
        id: verify_repo_owner
        if: ${{ github.repository_owner != 'dekiel' }}
        run: |
          echo "Using image-syncer workflow outside of kyma-project organisation is not supported."
          exit 1
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: simulate-auth-gcp
        run: echo "Using image-syncer workflow outside of kyma-project organisation is not supported." > ./creds.json

      - name: echo
        run: echo ${{ github.workspace }}
      
      #      - name: Authenticate in GCP
      #        id: authenticate_in_gcp
      #        uses: google-github-actions/auth@v2
      #        with:
      #          project_id: ${{ vars.GCP_KYMA_PROJECT_PROJECT_ID }}
      #          workload_identity_provider: ${{ vars.GH_COM_KYMA_PROJECT_GCP_WORKLOAD_IDENTITY_FEDERATION_PROVIDER }}
      
      - name: Sync Images
        id: sync_images
        uses: docker://europe-docker.pkg.dev/kyma-project/prod/test-infra/ko/image-syncer:v20240822-9b523f40
        with:
          entrypoint: /ko-app/image-syncer
          #args: bash -c "pwd; ls -lR /"
          args: --images-file=/github/workspace/external-images.yaml --target-repo-auth-key=/github/workspace/creds.json --dry-run true --debug true
